/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import static com.sun.javafx.fxml.expression.Expression.set;
import static com.sun.scenario.Settings.set;
import java.awt.Image;
import java.io.File;
import static java.lang.reflect.Array.set;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class telaurna extends javax.swing.JFrame {
    String caminho = "Z:/Desenvolvimento de Sistemas/2DSB/Vinicius Magalhães/urna legal/src/Som/urna.wav";
    String caminhob = "Z:/Desenvolvimento de Sistemas/2DSB/Vinicius Magalhães/urna legal/src/Som/Tecla.wav";

/**
 *
 * @author aluno
 */

    /**
     * Creates new form telaurna
     */
    public telaurna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbimagem = new javax.swing.JLabel();
        lbnum1 = new javax.swing.JLabel();
        lbnum2 = new javax.swing.JLabel();
        lbnum3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bcorrige = new javax.swing.JButton();
        bnulo = new javax.swing.JButton();
        bconfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbimagem.setBackground(new java.awt.Color(51, 255, 102));
        lbimagem.setForeground(new java.awt.Color(255, 255, 0));
        lbimagem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 51, 0)));
        getContentPane().add(lbimagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 150));

        lbnum1.setBackground(new java.awt.Color(51, 255, 102));
        lbnum1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbnum1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 51, 0)));
        getContentPane().add(lbnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 70));

        lbnum2.setBackground(new java.awt.Color(51, 255, 102));
        lbnum2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbnum2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 51, 0)));
        getContentPane().add(lbnum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 50, 70));

        lbnum3.setBackground(new java.awt.Color(51, 255, 102));
        lbnum3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbnum3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 51, 0)));
        getContentPane().add(lbnum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 50, 70));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Urna Eleitoral");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        b1.setBackground(new java.awt.Color(153, 153, 153));
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.setBorder(new javax.swing.border.MatteBorder(null));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 40, 30));

        b2.setBackground(new java.awt.Color(204, 204, 204));
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, 30));

        b3.setBackground(new java.awt.Color(204, 204, 204));
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 30));

        b4.setBackground(new java.awt.Color(204, 204, 204));
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 30));

        b5.setBackground(new java.awt.Color(204, 204, 204));
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 30));

        b6.setBackground(new java.awt.Color(204, 204, 204));
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 30));

        b7.setBackground(new java.awt.Color(204, 204, 204));
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        b8.setBackground(new java.awt.Color(204, 204, 204));
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b8MouseClicked(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        b9.setBackground(new java.awt.Color(204, 204, 204));
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b9MouseClicked(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 30));

        b0.setBackground(new java.awt.Color(204, 204, 204));
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b0MouseClicked(evt);
            }
        });
        getContentPane().add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, 30));

        bcorrige.setBackground(new java.awt.Color(255, 51, 51));
        bcorrige.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        bcorrige.setText("Corrige");
        bcorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcorrigeMouseClicked(evt);
            }
        });
        getContentPane().add(bcorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 223, 80, 30));

        bnulo.setBackground(new java.awt.Color(255, 255, 255));
        bnulo.setText("Branco");
        bnulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnuloMouseClicked(evt);
            }
        });
        getContentPane().add(bnulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 223, 80, 30));

        bconfirmar.setBackground(new java.awt.Color(0, 204, 51));
        bconfirmar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        bconfirmar.setText("Confirmar");
        bconfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bconfirmarMouseClicked(evt);
            }
        });
        getContentPane().add(bconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 223, 80, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setSize(562, 308);
    }//GEN-LAST:event_formWindowOpened

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
       escolha("1");
       
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        escolha("2");
        
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        escolha("3");
        
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        escolha("4");
        
    }//GEN-LAST:event_b4MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        escolha("5");
        
    }//GEN-LAST:event_b5MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
        escolha("6");
        
    }//GEN-LAST:event_b6MouseClicked

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
        escolha("7");
        
    }//GEN-LAST:event_b7MouseClicked

    private void b8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseClicked
        escolha("8");
        
    }//GEN-LAST:event_b8MouseClicked

    private void b9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseClicked
        escolha("9");
        
    }//GEN-LAST:event_b9MouseClicked

    private void b0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseClicked
        escolha("0");
        
    }//GEN-LAST:event_b0MouseClicked

    private void bcorrigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcorrigeMouseClicked
        lbnum1.setText("");
        lbnum2.setText("");
        lbnum3.setText("");
        lbimagem.setIcon(null);
    }//GEN-LAST:event_bcorrigeMouseClicked

    private void bnuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnuloMouseClicked
        JOptionPane.showConfirmDialog(null, "Você votou em Branco");
    }//GEN-LAST:event_bnuloMouseClicked

    private void bconfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bconfirmarMouseClicked
        Som p = new Som();
        p.Som(caminho);
    }//GEN-LAST:event_bconfirmarMouseClicked

    
    private void escolha(String info){
        Som p = new Som();
        p.Som(caminhob);
        if(lbnum1.getText() == ""){
            lbnum1.setText(info);
        }
        else{
            if(lbnum2.getText() == ""){
                lbnum2.setText(info);
            }
            else{
                lbnum3.setText(info);
                String numero = lbnum1.getText() + lbnum2.getText() + lbnum3.getText();
                //pegaCandidato(numero);
                CarregaCandidato(numero);
                
                
            }
        }
        //imgs();
    }  
    
    private void CarregaCandidato(String numero){
        ImageIcon img = new ImageIcon(this.getClass().getResource("/imgs/" + numero + ".png"));
        Image ima = img.getImage().getScaledInstance(lbimagem.getWidth(), lbimagem.getHeight(), Image.SCALE_DEFAULT);
        lbimagem.setIcon(new ImageIcon(ima));
     
     }
    
//    private void imgs(){
//        if (lbnum1.getText() == "0" && lbnum2.getText() == "0" && lbnum3.getText() == "7" ){
//            ImageIcon img = new ImageIcon(this.getClass().getResource("/imgs/bart.png"));
//            Image ima = img.getImage().getScaledInstance(lbimagem.getWidth(), lbimagem.getHeight(), Image.SCALE_DEFAULT);
//            lbimagem.setIcon(new ImageIcon(ima));
//        }
//        
//        if (lbnum1.getText() == "0" && lbnum2.getText() == "0" && lbnum3.getText() == "4" ){
//            ImageIcon img = new ImageIcon(this.getClass().getResource("/imgs/homer.png"));
//            Image ima = img.getImage().getScaledInstance(lbimagem.getWidth(), lbimagem.getHeight(), Image.SCALE_DEFAULT);
//            lbimagem.setIcon(new ImageIcon(ima));
//        }
//        
//        if (lbnum1.getText() == "0" && lbnum2.getText() == "0" && lbnum3.getText() == "5" ){
//            ImageIcon img = new ImageIcon(this.getClass().getResource("/imgs/Mordecai.jpg"));
//            Image ima = img.getImage().getScaledInstance(lbimagem.getWidth(), lbimagem.getHeight(), Image.SCALE_DEFAULT);
//            lbimagem.setIcon(new ImageIcon(ima));
//        }
//        
//        if (lbnum1.getText() == "0" && lbnum2.getText() == "0" && lbnum3.getText() == "8" ){
//            ImageIcon img = new ImageIcon(this.getClass().getResource("/imgs/Rigby.png"));
//            Image ima = img.getImage().getScaledInstance(lbimagem.getWidth(), lbimagem.getHeight(), Image.SCALE_DEFAULT);
//            lbimagem.setIcon(new ImageIcon(ima));
//        }
//        
//    }
    
    public class Som
       {
            public void Som (String soundName)
           {
//        Media pick = new Media(som); 
//        MediaPlayer player = new MediaPlayer(pick);
//        player.play();
 try
              {
                 AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
                 Clip clip = AudioSystem.getClip();
                 clip.open(audioInputStream);
                 clip.start();
            }
            catch (Exception ex)
           {
               System.out.println("Erro ao executar SOM!");
               ex.printStackTrace();
          }
        }
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaurna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bconfirmar;
    private javax.swing.JButton bcorrige;
    private javax.swing.JButton bnulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbimagem;
    private javax.swing.JLabel lbnum1;
    private javax.swing.JLabel lbnum2;
    private javax.swing.JLabel lbnum3;
    // End of variables declaration//GEN-END:variables
}
