/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.converte;
import Banco.conexao;
import static Banco.conexao.statement;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Aluno
 */
public class tela1 extends javax.swing.JFrame {
    
    double total = 0.00;
    double troco = 0.00;
    int ind = 0;
    converte conv = new converte();
    
    public double prec[] = new double[9];
    JLabel[] produto = new JLabel[9];
    JLabel[] tpreco = new JLabel[9];
    boolean travabebe = false;

  private void associaLabels()
    {
        produto[0] = lbImg1;
        produto[1] = lbImg2;
        produto[2] = lbImg3;
        produto[3] = lbImg4;
        produto[4] = lbImg5;
        produto[5] = lbImg6;
        produto[6] = lbImg7;
        produto[7] = lbImg8;
        produto[8] = lbImg9;
        
        tpreco[0] = lbPreco1;
        tpreco[1] = lbPreco2;
        tpreco[2] = lbPreco3;
        tpreco[3] = lbPreco4;
        tpreco[4] = lbPreco5;
        tpreco[5] = lbPreco6;
        tpreco[6] = lbPreco7;
        tpreco[7] = lbPreco8;
        tpreco[8] = lbPreco9;
        
    }
  

  private void carregaTela()
    {
       try     
       { 
        String sql = "SELECT * FROM tb01_produtos where tb01_seq between 1 and 9";
        
        conexao banco = new conexao();
        
        banco.conectar();
        
        ResultSet resultSet = statement.executeQuery(sql);  
        
        while (resultSet.next())
        {
          prec[ind] = parseDouble(resultSet.getString("tb01_preco"));   
          String preco = resultSet.getString("tb01_preco");
          tpreco[ind].setText(conv.ConvMoeda(preco));
          
          Image img = Toolkit.getDefaultToolkit().createImage(resultSet.getBytes("tb01_foto"));
          ImageIcon foto = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(produto[ind].getWidth(),produto[ind].getHeight(), Image.SCALE_DEFAULT));
          produto[ind].setIcon(foto);
         
          ind++;
        }
        
        banco.desconectar();
        resultSet.close();
        statement.close();  
        }
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }

    /**
     * Creates new form tela1
     */
    public tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImg8 = new javax.swing.JLabel();
        lbImg7 = new javax.swing.JLabel();
        lbImg4 = new javax.swing.JLabel();
        lbImg9 = new javax.swing.JLabel();
        lbImg2 = new javax.swing.JLabel();
        lbImg1 = new javax.swing.JLabel();
        lbImg5 = new javax.swing.JLabel();
        lbImg3 = new javax.swing.JLabel();
        lbImg6 = new javax.swing.JLabel();
        lbsaida = new javax.swing.JLabel();
        tecla3 = new javax.swing.JButton();
        tecla6 = new javax.swing.JButton();
        tecla5 = new javax.swing.JButton();
        tecla7 = new javax.swing.JButton();
        tecla8 = new javax.swing.JButton();
        tecla9 = new javax.swing.JButton();
        tecla1 = new javax.swing.JButton();
        tecla2 = new javax.swing.JButton();
        tecla4 = new javax.swing.JButton();
        j10pila = new javax.swing.JLabel();
        lbtroco = new javax.swing.JLabel();
        lbvisor = new javax.swing.JLabel();
        lbPreco6 = new javax.swing.JLabel();
        lbPreco1 = new javax.swing.JLabel();
        lbPreco2 = new javax.swing.JLabel();
        lbPreco3 = new javax.swing.JLabel();
        lbPreco4 = new javax.swing.JLabel();
        lbPreco5 = new javax.swing.JLabel();
        lbPreco7 = new javax.swing.JLabel();
        lbPreco8 = new javax.swing.JLabel();
        lbPreco9 = new javax.swing.JLabel();
        j2pila = new javax.swing.JLabel();
        j5pila = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImg8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 333, 106, 126));

        lbImg7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 333, 106, 126));

        lbImg4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 177, 106, 126));

        lbImg9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg9, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 333, 106, 126));

        lbImg2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 21, 106, 126));

        lbImg1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 21, 106, 126));

        lbImg5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 177, 106, 126));

        lbImg3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 21, 106, 126));

        lbImg6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbImg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 177, 106, 126));

        lbsaida.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        lbsaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbsaidaMouseClicked(evt);
            }
        });
        getContentPane().add(lbsaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 106, 126));

        tecla3.setBackground(new java.awt.Color(0, 102, 102));
        tecla3.setForeground(new java.awt.Color(255, 255, 255));
        tecla3.setText("3");
        tecla3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla3ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 177, 60, 60));

        tecla6.setBackground(new java.awt.Color(0, 102, 102));
        tecla6.setForeground(new java.awt.Color(255, 255, 255));
        tecla6.setText("6");
        tecla6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla6ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 244, 60, 60));

        tecla5.setBackground(new java.awt.Color(0, 102, 102));
        tecla5.setForeground(new java.awt.Color(255, 255, 255));
        tecla5.setText("5");
        tecla5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla5ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 244, 60, 60));

        tecla7.setBackground(new java.awt.Color(0, 102, 102));
        tecla7.setForeground(new java.awt.Color(255, 255, 255));
        tecla7.setText("7");
        tecla7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla7ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 311, 60, 60));

        tecla8.setBackground(new java.awt.Color(0, 102, 102));
        tecla8.setForeground(new java.awt.Color(255, 255, 255));
        tecla8.setText("8");
        tecla8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla8ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla8, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 311, 60, 60));

        tecla9.setBackground(new java.awt.Color(0, 102, 102));
        tecla9.setForeground(new java.awt.Color(255, 255, 255));
        tecla9.setText("9");
        tecla9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla9ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla9, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 311, 60, 60));

        tecla1.setBackground(new java.awt.Color(0, 102, 102));
        tecla1.setForeground(new java.awt.Color(255, 255, 255));
        tecla1.setText("1");
        tecla1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla1ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 177, 60, 60));

        tecla2.setBackground(new java.awt.Color(0, 102, 102));
        tecla2.setForeground(new java.awt.Color(255, 255, 255));
        tecla2.setText("2");
        tecla2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla2ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 177, 60, 60));

        tecla4.setBackground(new java.awt.Color(0, 102, 102));
        tecla4.setForeground(new java.awt.Color(255, 255, 255));
        tecla4.setText("4");
        tecla4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tecla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecla4ActionPerformed(evt);
            }
        });
        getContentPane().add(tecla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 244, 60, 60));

        j10pila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j10pilaMouseClicked(evt);
            }
        });
        getContentPane().add(j10pila, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 80, 40));

        lbtroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtroco.setText("TROCO");
        lbtroco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbtroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 389, 194, 40));

        lbvisor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbvisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbvisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbvisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 119, 194, 40));

        lbPreco6.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco6.setText("jLabel7");
        getContentPane().add(lbPreco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        lbPreco1.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco1.setText("jLabel7");
        getContentPane().add(lbPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lbPreco2.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco2.setText("jLabel7");
        getContentPane().add(lbPreco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        lbPreco3.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco3.setText("jLabel7");
        getContentPane().add(lbPreco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        lbPreco4.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco4.setText("jLabel7");
        getContentPane().add(lbPreco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        lbPreco5.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco5.setText("jLabel7");
        getContentPane().add(lbPreco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        lbPreco7.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco7.setText("jLabel7");
        getContentPane().add(lbPreco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        lbPreco8.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco8.setText("jLabel7");
        getContentPane().add(lbPreco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        lbPreco9.setForeground(new java.awt.Color(255, 255, 255));
        lbPreco9.setText("jLabel7");
        getContentPane().add(lbPreco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        j2pila.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j2pila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j2pila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2pilaMouseClicked(evt);
            }
        });
        getContentPane().add(j2pila, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 40));

        j5pila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5pilaMouseClicked(evt);
            }
        });
        getContentPane().add(j5pila, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 80, 40));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tecla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla3ActionPerformed
        if( total >= prec[2] && travabebe==false)
        {
            lbsaida.setIcon(produto[2].getIcon());
            produto[2].setIcon(null);
            troco = total - prec[2];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
        
    }//GEN-LAST:event_tecla3ActionPerformed

    private void tecla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla6ActionPerformed
       if( total >= prec[5] && travabebe==false)
        {
            lbsaida.setIcon(produto[5].getIcon());
            produto[5].setIcon(null);
            troco = total - prec[5];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla6ActionPerformed

    private void tecla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla5ActionPerformed
       if( total >= prec[4] && travabebe==false)
        {
            lbsaida.setIcon(produto[4].getIcon());
            produto[4].setIcon(null);
            troco = total - prec[4];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla5ActionPerformed

    private void tecla7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla7ActionPerformed
      if( total >= prec[6] && travabebe==false)
        {
            lbsaida.setIcon(produto[6].getIcon());
            produto[6].setIcon(null);
            troco = total - prec[6];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla7ActionPerformed

    private void tecla8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla8ActionPerformed
       if( total >= prec[7] && travabebe==false)
        {
            lbsaida.setIcon(produto[7].getIcon());
            produto[7].setIcon(null);
            troco = total - prec[7];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla8ActionPerformed

    private void tecla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla9ActionPerformed
        if( total >= prec[8] && travabebe==false)
        {
            lbsaida.setIcon(produto[8].getIcon());
            produto[8].setIcon(null);
            troco = total - prec[8];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla9ActionPerformed

    private void tecla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla1ActionPerformed
        if( total >= prec[0] && travabebe==false)
        {
            lbsaida.setIcon(produto[0].getIcon());
            produto[0].setIcon(null);
            troco = total - prec[0];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla1ActionPerformed

    private void tecla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla2ActionPerformed
        if( total >= prec[1] && travabebe==false)
        {
            lbsaida.setIcon(produto[1].getIcon());
            produto[1].setIcon(null);
            troco = total - prec[1];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla2ActionPerformed

    private void tecla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecla4ActionPerformed
        if( total >= prec[3] && travabebe==false)
        {
            lbsaida.setIcon(produto[3].getIcon());
            produto[3].setIcon(null);
            troco = total - prec[3];
            lbtroco.setText(String.valueOf(troco));
            travabebe = true;
        }
    }//GEN-LAST:event_tecla4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/Imagens/10_pila.jpg"));     

        Image imag = imagem.getImage().getScaledInstance(j10pila.getWidth(), j10pila.getHeight(), Image.SCALE_DEFAULT);

        j10pila.setIcon(new ImageIcon(imag));
        
        ImageIcon image = new  ImageIcon(this.getClass().getResource("/Imagens/5_pila.jpg"));     

        Image ima = image.getImage().getScaledInstance(j5pila.getWidth(), j5pila.getHeight(), Image.SCALE_DEFAULT);

        j5pila.setIcon(new ImageIcon(ima));
        
        ImageIcon Imagem = new  ImageIcon(this.getClass().getResource("/Imagens/2_pila.jpg"));     

        Image im = Imagem.getImage().getScaledInstance(j2pila.getWidth(), j2pila.getHeight(), Image.SCALE_DEFAULT);

        j2pila.setIcon(new ImageIcon(im));
        
        associaLabels();
        carregaTela();
    }//GEN-LAST:event_formWindowOpened

    private void j2pilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2pilaMouseClicked
       if(travabebe==false){
           total = total + 2;
        lbvisor.setText(String.valueOf(total));
        
       }
        
    }//GEN-LAST:event_j2pilaMouseClicked

    private void j5pilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5pilaMouseClicked

        if(travabebe==false){
           total = total + 5;
        lbvisor.setText(String.valueOf(total));
       }
        
    }//GEN-LAST:event_j5pilaMouseClicked

    private void j10pilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j10pilaMouseClicked
       if(travabebe==false){
           total = total + 10;
        lbvisor.setText(String.valueOf(total));
        
       }
    }//GEN-LAST:event_j10pilaMouseClicked

    private void lbsaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbsaidaMouseClicked
        if(!lbsaida.getIcon().equals(null)){
            tela1 tela = new tela1();
            tela.setVisible(true);
            dispose();
        
        }
    }//GEN-LAST:event_lbsaidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j10pila;
    private javax.swing.JLabel j2pila;
    private javax.swing.JLabel j5pila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbImg1;
    private javax.swing.JLabel lbImg2;
    private javax.swing.JLabel lbImg3;
    private javax.swing.JLabel lbImg4;
    private javax.swing.JLabel lbImg5;
    private javax.swing.JLabel lbImg6;
    private javax.swing.JLabel lbImg7;
    private javax.swing.JLabel lbImg8;
    private javax.swing.JLabel lbImg9;
    private javax.swing.JLabel lbPreco1;
    private javax.swing.JLabel lbPreco2;
    private javax.swing.JLabel lbPreco3;
    private javax.swing.JLabel lbPreco4;
    private javax.swing.JLabel lbPreco5;
    private javax.swing.JLabel lbPreco6;
    private javax.swing.JLabel lbPreco7;
    private javax.swing.JLabel lbPreco8;
    private javax.swing.JLabel lbPreco9;
    private javax.swing.JLabel lbsaida;
    private javax.swing.JLabel lbtroco;
    private javax.swing.JLabel lbvisor;
    private javax.swing.JButton tecla1;
    private javax.swing.JButton tecla2;
    private javax.swing.JButton tecla3;
    private javax.swing.JButton tecla4;
    private javax.swing.JButton tecla5;
    private javax.swing.JButton tecla6;
    private javax.swing.JButton tecla7;
    private javax.swing.JButton tecla8;
    private javax.swing.JButton tecla9;
    // End of variables declaration//GEN-END:variables
}
